[package]
name = "timu6502asm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
log = "0.4.22"
simplelog = "^0.12.2"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"

[dev-dependencies]
rstest = "0.22.0"
